// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjsrmwuanyywwebmzsmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqc3Jtd3Vhbnl5d3dlYm16c21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTAzNTksImV4cCI6MjA2MzM2NjM1OX0.XH-m-l2Jjh23ekxrTBCOrrNJX2hXx-cgN_Vh1B_QANk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);